services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: portal_tik_app

    working_dir: /var/www

    volumes:
      - .:/var/www

    restart: unless-stopped
    
    env_file:
      - .env

    networks:
      - laravel


  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: portal_tik_queue

    working_dir: /var/www

    volumes:
      - .:/var/www

    env_file:
      - .env

    command: php artisan queue:work --sleep=1 --tries=3 --timeout=30
    restart: unless-stopped

    depends_on:
      - app
      - mysql
      - mqtt

    networks:
      - laravel


  mqtt_listener:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: portal_tik_mqtt_listener

    working_dir: /var/www

    volumes:
      - .:/var/www

    env_file:
      - .env

    command: php artisan mqtt:listen
    restart: unless-stopped

    depends_on:
      - app
      - mqtt
      - mysql

    networks:
      - laravel


  nginx:
    image: nginx:alpine

    container_name: portal_tik_nginx

    ports:
      - "8000:80"

    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app
    
    restart: unless-stopped

    networks:
      - laravel


  mysql:
    image: mysql:8.4

    container_name: portal_tik_mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - laravel


  mqtt:
    image: eclipse-mosquitto

    container_name: portal_tik_mqtt

    ports:
      - "1883:1883"

    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    
    restart: unless-stopped

    networks:
      - laravel

  
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: portal_tik_mediamtx
    env_file:
      - .env
    environment:
      MTX_PATHS_GATE1_SOURCE: publisher
    ports:
      - "8554:8554"
      - "8889:8889"
      - "8189:8189/udp"
      - "8888:8888"
    # volumes:
    #   - ./docker/mediamtx/mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    networks:
      - laravel


volumes:
  mysql_data:


networks:
  laravel: